# Generated by Django 4.2.19 on 2025-03-27 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="date_posted",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
